/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_1ed4438c (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// This file provides a simple key-value interface for storing Figma Make data.
// We changed 'jsr:' to 'npm:' so VS Code understands it.
// @ts-ignore
import { createClient } from "npm:@supabase/supabase-js@2";

// @ts-ignore: Deno is defined in the Edge Runtime, but VS Code might complain without the Deno extension.
const client = () => createClient(
    // @ts-ignore
    Deno.env.get("SUPABASE_URL")!,
    // @ts-ignore
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from("kv_store_1ed4438c").upsert({
        key,
        value
    });
    if (error) {
        throw new Error(error.message);
    }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_1ed4438c").select("value").eq("key", key).maybeSingle();
    if (error) {
        throw new Error(error.message);
    }
    return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from("kv_store_1ed4438c").delete().eq("key", key);
    if (error) {
        throw new Error(error.message);
    }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from("kv_store_1ed4438c").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
        throw new Error(error.message);
    }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_1ed4438c").select("value").in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
    // FIX: Typisierung für 'd' hinzugefügt (any)
    return data?.map((d: any) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from("kv_store_1ed4438c").delete().in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_1ed4438c").select("key, value").like("key", prefix + "%");
    if (error) {
        throw new Error(error.message);
    }
    // FIX: Typisierung für 'd' hinzugefügt (any)
    return data?.map((d: any) => d.value) ?? [];
};